#!/usr/bin/env node
/**
 * faceted-prompting のライブラリを使って skills/agents を一括生成する。
 * Usage: node .faceted/generate.mjs [composition-name]
 *   引数なし: 全 composition を生成
 *   引数あり: 指定した composition のみ生成
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
// Simple YAML parser for flat key-value + list compositions (no nested objects)
function parseSimpleYaml(text) {
  const result = {};
  let currentKey = null;
  let currentList = null;
  for (const line of text.split('\n')) {
    const listMatch = line.match(/^\s+-\s+(.+)$/);
    if (listMatch && currentKey) {
      if (!currentList) currentList = [];
      currentList.push(listMatch[1].trim());
      result[currentKey] = currentList;
      continue;
    }
    const kvMatch = line.match(/^(\w[\w-]*):\s*(.*)$/);
    if (kvMatch) {
      if (currentList) currentList = null;
      currentKey = kvMatch[1];
      const val = kvMatch[2].trim();
      if (val === '' || val === '[]') {
        // Next lines may be list items
        result[currentKey] = val === '[]' ? [] : undefined;
      } else {
        result[currentKey] = val.replace(/^["']|["']$/g, '');
        currentKey = null;
      }
      continue;
    }
  }
  return result;
}

const HOME = homedir();
const FACETED_ROOT = join(HOME, '.faceted');
const FACETS_ROOT = join(FACETED_ROOT, 'facets');
const COMPOSITIONS_DIR = join(FACETED_ROOT, 'compositions');

// --- Extra frontmatter per asset (not supported by composition YAML schema) ---
const EXTRA_FRONTMATTER = {
  // Skills
  'agent-memory': { type: 'skill', extra: { 'user-invocable': false } },
  'recall':       { type: 'skill', extra: { 'user-invocable': false } },
  'remember':     { type: 'skill', extra: { 'argument-hint': '"[保存したいメモや情報]"' } },
  'pr':           { type: 'skill', extra: { 'disable-model-invocation': true, 'allowed-tools': 'Bash(gh *), Bash(git *)' } },
  'skill-auditor': { type: 'skill', extra: { 'disable-model-invocation': true } },
  // Agents
  'developer':         { type: 'agent', extra: { tools: 'Bash, Read, Write, Edit, Grep, Glob', maxTurns: 20 } },
  'tester':            { type: 'agent', extra: { tools: 'Bash, Read, Write, Edit, Grep, Glob', maxTurns: 15 } },
  'reviewer':          { type: 'agent', extra: { tools: 'Bash, Read, Grep, Glob', maxTurns: 15 } },
  'planner':           { type: 'agent', extra: { tools: 'Bash, Read, Grep, Glob', maxTurns: 15 } },
  'planner-frontend':  { type: 'agent', extra: { tools: 'Bash, Read, Grep, Glob', maxTurns: 15 } },
  'pr-maker':          { type: 'agent', extra: { tools: 'Bash, Read, Grep, Glob', maxTurns: 8 } },
  'cross-reviewer':    { type: 'agent', extra: { tools: 'Bash, Read, Grep, Glob', maxTurns: 10 } },
  'address':           { type: 'agent', extra: { tools: 'Bash, Read, Write, Edit, Grep, Glob', maxTurns: 20 } },
};

function readFacet(kind, ref, compositionDir) {
  // Resource path (starts with ../ or ./)
  if (ref.startsWith('./') || ref.startsWith('../')) {
    const resolved = join(compositionDir, ref);
    return readFileSync(resolved, 'utf-8');
  }
  // Facet name
  const facetPath = join(FACETS_ROOT, kind, `${ref}.md`);
  if (!existsSync(facetPath)) {
    throw new Error(`Missing ${kind} facet "${ref}": ${facetPath}`);
  }
  return readFileSync(facetPath, 'utf-8');
}

function loadComposition(filePath) {
  const raw = readFileSync(filePath, 'utf-8');
  return parseSimpleYaml(raw);
}

function renderDocument(def, compositionDir) {
  const lines = [];

  // Frontmatter
  const meta = EXTRA_FRONTMATTER[def.name] || { type: 'skill', extra: {} };
  lines.push('---');
  lines.push(`name: ${def.name}`);
  if (def.description) lines.push(`description: ${JSON.stringify(def.description)}`);
  for (const [k, v] of Object.entries(meta.extra)) {
    lines.push(`${k}: ${v}`);
  }
  lines.push('---');
  lines.push('');
  lines.push('<!-- Generated by faceted-prompting. Do not edit manually. -->');
  lines.push('');

  // Persona
  const personaBody = readFacet('persona', def.persona, compositionDir);
  lines.push('## Persona');
  lines.push('');
  lines.push(personaBody.trim());
  lines.push('');

  // Policies
  if (def.policies?.length > 0) {
    lines.push('## Policies');
    lines.push('');
    for (const ref of def.policies) {
      const body = readFacet('policies', ref, compositionDir);
      lines.push(`### ${ref}`);
      lines.push('');
      lines.push(body.trim());
      lines.push('');
    }
  }

  // Knowledge
  if (def.knowledge?.length > 0) {
    lines.push('## Knowledge');
    lines.push('');
    for (const ref of def.knowledge) {
      const body = readFacet('knowledge', ref, compositionDir);
      lines.push(`### ${ref}`);
      lines.push('');
      lines.push(body.trim());
      lines.push('');
    }
  }

  // Instruction
  if (def.instruction) {
    const body = readFacet('output-contracts', def.instruction, compositionDir);
    lines.push('## Instruction');
    lines.push('');
    lines.push(body.trim());
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

const OUTPUT_ROOT = join(FACETED_ROOT, 'output');

function outputPath(name) {
  const meta = EXTRA_FRONTMATTER[name];
  if (!meta) {
    console.warn(`Warning: no metadata for "${name}", defaulting to skill`);
    return join(OUTPUT_ROOT, 'skills', name, 'SKILL.md');
  }
  if (meta.type === 'agent') {
    return join(OUTPUT_ROOT, 'agents', `${name}.md`);
  }
  return join(OUTPUT_ROOT, 'skills', name, 'SKILL.md');
}

function generate(filter) {
  const files = readdirSync(COMPOSITIONS_DIR).filter(f => f.endsWith('.yaml') || f.endsWith('.yml'));

  for (const file of files) {
    const filePath = join(COMPOSITIONS_DIR, file);
    const def = loadComposition(filePath);
    const name = def.name;

    if (filter && filter !== name) continue;

    const content = renderDocument(def, COMPOSITIONS_DIR);
    const out = outputPath(name);

    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, content, 'utf-8');
    console.log(`Generated: ${out}`);
  }
}

const filter = process.argv[2] || null;
generate(filter);
