# ~/.config/yazi/keymap.toml

[mgr]
prepend_keymap = [
  { on = ["g", "d"], run = "cd ~/Downloads", desc = "Go to Downloads" },
  { on = ["g", "r"], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to git root" },
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },
]
