# ~/.config/yazi/yazi.toml

[mgr]
ratio        = [1, 4, 3]
sort_by      = "natural"
sort_dir_first = true
linemode     = "size"
show_hidden  = true
show_symlink = true
scrolloff    = 5

[preview]
wrap         = "no"
tab_size     = 2
max_width    = 600
max_height   = 900
image_filter = "lanczos3"
image_quality = 75

[opener]
edit = [
  { run = "$EDITOR %s", block = true, for = "unix" },
]
open = [
  { run = "open %s", desc = "Open", for = "macos" },
]
extract = [
  { run = "ya pub extract --list %s", desc = "Extract here" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "open" },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
suppress_preload = false
